spring:
  data:
    redis:
      host: 47.97.219.138
      port: 6379
      password: '195956'
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms

